
bind_address = "0.0.0.0:3338"
log_level = "DEBUG"


[appcfg.keys]
connection = "ws://surrealdb:8000"
namespace = "test"
database = "key"
table = "keys"

[appcfg.quotekeys]
connection = "ws://surrealdb:8000"
namespace = "test"
database = "key"
table = "quotes"

[appcfg]
starting_derivation_path = "m/129372'/0/0"
