[package]
name = "bcr-wdc-e2e-tests"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bcr-wdc-webapi = {workspace = true, features = ["test-utils"]}
cashu.workspace = true
chrono.workspace = true
reqwest = {workspace = true, features = ["json"]}
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
tracing = {workspace = true }
tracing-subscriber = {workspace = true, features = ["serde"]}
bcr-wdc-utils = {workspace = true, features = ["test-utils"] }
bcr-wdc-key-service = {workspace = true, features = ["test-utils"]}
bcr-ebill-core.workspace = true
bitcoin.workspace = true
bdk_wallet = {workspace = true}
rand = {workspace = true}
serde.workspace = true
config = {workspace = true}
anyhow = {workspace = true}