[workspace]
resolver = "2"


members = [ "crates/bcr-wdc-webapi", "crates/bcr-wdc-keys", "crates/bcr-wdc-quote-service", "crates/bcr-wdc-swap-service", "crates/bcr-wdc-key-service", "crates/bcr-wdc-key-client"]


[workspace.dependencies]
anyhow = {version = "1"}
async-trait = {version = "0.1"}
axum = {version = "0.7", features = ["macros"]}
bcr-ebill-core = {git = "https://github.com/BitcreditProtocol/E-Bill.git", branch = "master"}
bitcoin = {version = "0.32"}
borsh = {version = "1.5", features = ["derive"]}
cashu = {version = "0.7", default-features = false, features = ["mint", "swagger"]}
chrono = {version = "0.4", features = ["serde"]}
config = {version = "0.15"}
env_logger = {version = "0.11"}
futures = {version = "0.3"}
log = {version = "0.4", features = ["serde"]}
mockall = {version = "0.13"}
rand = {version = "0.9"}
rust_decimal = {version = "1"}
serde = {version = "1", features = ["derive"]}
surrealdb = {version = "2.2", features = ["kv-mem"]}
strum = {version = "0"}
thiserror = {version = "2"}
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
utoipa = {version = "4", features = ["axum_extras", "chrono", "uuid", "decimal"]} # compatibility with cdk
utoipa-swagger-ui = {version = "7", features = ["axum"]}
uuid = {version = "1", features = ["serde", "v4"]}
