[workspace]
    
members = [ "crates/wildcat"]

[workspace.dependencies]

async-trait = {version = "0.1"}
axum = {version = "0.6", features = ["macros"]}
bitcoin = {version = "0.32"}
cdk = {version = "0.6"}
log = {version = "0.4", features = ["serde"]}
serde = {version = "1.0", features = ["derive"]}
surrealdb = {version = "2.2", features = ["kv-mem"]}
tokio = {version = "1.4", features = ["macros", "rt-multi-thread"]}
uuid = {version = "1.11", features = ["serde", "v4"]}
