services:
  ######################################################################################## bcr-wdc

  ebpp:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-ebpp:${IMAGE_TAG:-latest}
    pull_policy: always
    volumes:
      - ./docker/ebpp/config.toml:/ebpp/config.toml
      - ${DATA_PATH}/ebpp/:/data/
    environment:
      - EBPP_MNEMONIC=${MINT_SEED_PHRASE}
      - EBPP__APPCFG__ONCHAIN__NETWORK=testnet
      - EBPP__APPCFG__ONCHAIN__STORE_PATH=/data/testnet
      - EBPP__APPCFG__TREASURY_SERVICE_PUBLIC_KEY=${EBPP__APPCFG__TREASURY_SERVICE_PUBLIC_KEY}
      - EBPP__APPCFG__ELECTRUM_URL=100.107.165.30:50001

  key-service:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-key-service:${IMAGE_TAG:-latest}
    pull_policy: always
    environment:
      - KEY_SERVICE_MNEMONIC=${MINT_SEED_PHRASE}

  swap-service:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-swap-service:${IMAGE_TAG:-latest}
    pull_policy: always

  treasury-service:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-treasury-service:${IMAGE_TAG:-latest}
    pull_policy: always
    volumes:
      - ./docker/treasury-service/config.toml:/treasury-service/config.toml
      - ${DATA_PATH}/treasury-service/:/data/
    environment:
      - TREASURY_SERVICE_MNEMONIC=${MINT_SEED_PHRASE}

  quote-service:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-quote-service:${IMAGE_TAG:-latest}
    pull_policy: always

  wallet-aggregator:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-wallet-aggregator:${IMAGE_TAG:-latest}
    pull_policy: always

  admin-aggregator:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-admin-aggregator:${IMAGE_TAG:-latest}
    pull_policy: always

  ######################################################################################## clowder

  signatory:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/clowder:${IMAGE_TAG:-latest}
    pull_policy: always

  clowder-node:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/clowder:${IMAGE_TAG:-latest}
    pull_policy: always
    environment:
      - CLWDR__ELECTRUM_CONFIG__RPC_URL=tcp://100.107.165.30:50001
      - CLWDR__ELECTRUM_CONFIG__NETWORK=testnet
    ports:
      - "3010:3010"
      - 5001:5001/udp
    volumes:
      - ./docker/clowder-node/settings.toml:/clowder/settings.toml

  ######################################################################################## clowder-beta

  signatory-beta:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/clowder:${IMAGE_TAG:-latest}
    pull_policy: always

  clowder-beta:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/clowder:${IMAGE_TAG:-latest}
    pull_policy: always
    environment:
      - CLWDR__ELECTRUM_CONFIG__RPC_URL=tcp://100.107.165.30:50001
      - CLWDR__ELECTRUM_CONFIG__NETWORK=testnet

  ######################################################################################## wildcat-auxiliary

  ebill-service:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-ebill-service:${IMAGE_TAG:-latest}
    pull_policy: always
    ports:
      - "3338:3338"
    environment:
      - EBILL__APPCFG__NOSTR_CFG__RELAYS=${EBILL__APPCFG__NOSTR_CFG__RELAYS}

  eic-service:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-eic-service:${IMAGE_TAG:-latest}
    pull_policy: always
    environment:
      - EIC__APPCFG__MAILJET_CONFIG__API_KEY=${EIC__APPCFG__MAILJET_CONFIG__API_KEY}
      - EIC__APPCFG__MAILJET_CONFIG__API_SECRET_KEY=${EIC__APPCFG__MAILJET_CONFIG__API_SECRET_KEY}
      - EIC_MNEMONIC=${MINT_SEED_PHRASE}

  ens-service:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-ens-service:${IMAGE_TAG:-latest}
    pull_policy: always
    environment:
      - ENS__APPCFG__MAILJET_CONFIG__API_KEY=${ENS__APPCFG__MAILJET_CONFIG__API_KEY}
      - ENS__APPCFG__MAILJET_CONFIG__API_SECRET_KEY=${ENS__APPCFG__MAILJET_CONFIG__API_SECRET_KEY}

  ######################################################################################## bcr-wdc-bootstrap

  ebill-service-bootstrap:
    image: alpine/curl:8.14.1
    depends_on:
      ebill-service:
        condition: service_healthy
    restart: "no"
    environment:
      MINT_SEED_PHRASE: ${MINT_SEED_PHRASE}
      MINT_IDENTITY: ${MINT_IDENTITY}
    entrypoint:
      - /bin/sh
      - -eu
      - -c
      - |
        echo "========== Configuring Node ID =========="
        echo -e "========== Setting Seed Phrase =========="
        curl -sSf \
            -X PUT http://ebill-service:3338/v1/admin/identity/seed/recover \
            -H "Content-Type: application/json" \
            -d '{"seed_phrase":"$MINT_SEED_PHRASE"}'
        echo -e "\n========== Creating Node ID =========="
        curl -s \
            -X POST http://ebill-service:3338/v1/admin/identity/create \
            -H "Content-Type: application/json" \
            -d '$MINT_IDENTITY'
        echo -e "\n========== Finish Node ID Config ==========\n"

 ######################################################################################## dashboard

  dashboard-ui:
    image: ghcr.io/bitcreditprotocol/bcr-wdc-dashboard-ui:${IMAGE_TAG:-latest}
    pull_policy: always
    ports:
      - "8181:80"
    environment:
      - VITE_API_BASE_URL=${DASHBOARD_VITE_API_BASE_URL}
      - VITE_KEYCLOAK_URL=${DASHBOARD_VITE_KEYCLOAK_URL}
      - VITE_KEYCLOAK_REALM=${DASHBOARD_VITE_KEYCLOAK_REALM}
      - VITE_KEYCLOAK_CLIENT_ID=${DASHBOARD_VITE_KEYCLOAK_CLIENT_ID}
      - VITE_API_MOCKING_ENABLED=false
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ######################################################################################## 3rd parties

  surrealdb:
    volumes:
      - ${DATA_PATH}/surrealdb:/data
    ports:
      - "8000:8000"

  cdk-mintd:
    volumes:
      - ${DATA_PATH}/cdk-mintd:/root/.cdk-mintd/
    environment:
      - CDK_MINTD_MNEMONIC=${MINT_SEED_PHRASE}

networks:
  default:
    external: true
    name: wildcat_default
