services:

  ######################################################################################## bcr-wdc

  ebpp:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-ebpp:${IMAGE_TAG:-latest}
    volumes:
      - ./docker/ebpp/config.toml:/ebpp/config.toml
      - ${DATA_PATH}/ebpp/:/data/

  key-service:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-key-service:${IMAGE_TAG:-latest}

  swap-service:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-swap-service:${IMAGE_TAG:-latest}

  treasury-service:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-treasury-service:${IMAGE_TAG:-latest}
    volumes:
      - ./docker/treasury-service/config.toml:/treasury-service/config.toml
      - ${DATA_PATH}/treasury-service/:/data/

  quote-service:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-quote-service:${IMAGE_TAG:-latest}

  eiou-service:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-eiou-service:${IMAGE_TAG:-latest}

  wallet-aggregator:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-wallet-aggregator:${IMAGE_TAG:-latest}

  ebill-service:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-ebill-service:${IMAGE_TAG:-latest}
    ports:
      - "3338:3338"  

  balance-collector:
    image: europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/bcr-wdc-balance-collector:${IMAGE_TAG:-latest}

  ######################################################################################## bcr-wdc-bootstrap

  ebill-service-bootstrap:
    image: alpine/curl:8.14.1
    depends_on:
      ebill-service:
        condition: service_healthy
    restart: "no"
    environment:
      MINT_SEED_PHRASE: ${MINT_SEED_PHRASE}
      MINT_IDENTITY: ${MINT_IDENTITY}
    entrypoint:
      - /bin/sh
      - -eu
      - -c
      - |
        echo "========== Configuring Node ID =========="
        echo -e "========== Setting Seed Phrase =========="
        curl -sSf \
            -X PUT http://ebill-service:3338/v1/identity/seed/recover \
            -H "Content-Type: application/json" \
            -d '{"seed_phrase":"$MINT_SEED_PHRASE"}'
        echo -e "\n========== Creating Node ID =========="
        curl -s \
            -X POST http://ebill-service:3338/v1/identity/create \
            -H "Content-Type: application/json" \
            -d '$MINT_IDENTITY'
        echo -e "\n========== Finish Node ID Config ==========\n"

 ######################################################################################## 3rd parties

  surrealdb:
    volumes:
      - ${DATA_PATH}/surrealdb:/data

  bitcoin-core:
    volumes:
      - ./docker/bitcoin-core/bitcoin.conf:/home/bitcoin/bitcoin.conf
      - ${DATA_PATH}/bitcoin-core/:/home/bitcoin/data

networks:
  default:
    external: true
    name: wildcat_default