services:

  key-service:
    image: wildcat/key-service
    pull_policy: never
    ports:
      - "3335:3338"
    depends_on:
      surrealdb:
        condition: service_healthy
    volumes:
      - ./docker/key-service/config.toml:/key-service/config.toml
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3338/api-docs/openapi.json"]
      interval: 10s
      timeout: 10s
      retries: 20

  treasury-service:
    image: wildcat/treasury-service
    pull_policy: never
    ports:
      - "3336:3338"
    depends_on:
      surrealdb:
        condition: service_healthy
    volumes:
      - ./docker/treasury-service/config.toml:/treasury-service/config.toml
      - ./.docker_data/treasury-service/:/data/

  swap-service:
    image: wildcat/swap-service
    pull_policy: never
    ports:
      - "3337:3338"
    depends_on:
      surrealdb:
        condition: service_healthy
      key-service:
        condition: service_healthy
    volumes:
      - ./docker/swap-service/config.toml:/swap-service/config.toml

  quote-service:
    image: wildcat/quote-service
    pull_policy: never
    ports:
      - "3338:3338"
    depends_on:
      surrealdb:
        condition: service_healthy
      key-service:
        condition: service_healthy
      treasury-service:
        condition: service_started
    volumes:
      - ./docker/quote-service/config.toml:/quote-service/config.toml
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3338/api-docs/openapi.json"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s
      start_interval: 3s

  surrealdb:
    image: surrealdb/surrealdb:latest
    volumes:
      - ./.docker_data/surrealdb:/data
    command:
      - start
      - --unauthenticated
      - rocksdb:/data/database.db
    user: ${UID}:${GID}
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "/surreal", "is-ready" ]
      interval: 5s
      retries: 5

  cdk_mint:
    image: thesimplekid/cdk-mintd:v0.7.4@sha256:9da05978f0e18a11ff08a2f6494d87bc2efdc1d70f733278f0c5dd4f74db1579
    volumes:
      - ./docker/cdk-mintd/config.toml:/root/.cdk-mintd/config.toml
    restart: unless-stopped
    command: ["cdk-mintd"]
    ports:
      - "8085:8085"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://127.0.0.1:8085/v1/info || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s
      start_interval: 3s
