services:

  eiou-service:
    extends:
        file: common-services.yml
        service: eiou-service

  key-service:
    extends:
      file: common-services.yml
      service: key-service

  treasury-service:
    extends:
      file: common-services.yml
      service: treasury-service

  swap-service:
    extends:
      file: common-services.yml
      service: swap-service

  quote-service:
    extends:
      file: common-services.yml
      service: quote-service

  wallet-aggregator:
    extends:
        file: common-services.yml
        service: wallet-aggregator

  surrealdb:
    extends:
      file: common-services.yml
      service: surrealdb

  cdk-mintd:
    extends:
      file: common-services.yml
      service: cdk-mintd

  ebpp:
    extends:
      file: common-services.yml
      service: ebpp
    environment:
      - EBPP_MNEMONIC=abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about
      - EBPP__APPCFG__ONCHAIN__NETWORK=testnet
      - EBPP__APPCFG__ONCHAIN__STORE_PATH=/data/testnet

  ebill-service:
    extends:
      file: common-services.yml
      service: ebill-service

  bff-wallet-service:
    extends:
        file: common-services.yml
        service: bff-wallet-service

  bff-dashboard-service:
    extends:
        file: common-services.yml
        service: bff-dashboard-service

  bitcoin-core:
    extends:
      file: common-services.yml
      service: bitcoin-core
    command:
      - -printtoconsole
      - --testnet=1
      - -conf=/home/bitcoin/bitcoin.conf
    healthcheck:
      test: ["CMD", "bitcoin-cli", "--testnet", "getconnectioncount"]

  keycloak:
    extends:
        file: common-services.yml
        service: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_SECRET}
      WDC_DASHBOARD_URL: ${WDC_DASHBOARD_URL}
      KEYCLOAK_BFF_DASHBOARD_SECRET: ${KEYCLOAK_BFF_DASHBOARD_SECRET}
      KEYCLOAK_BFF_DASHBOARD_ALLOWED_ORIGINS: ${KEYCLOAK_BFF_DASHBOARD_ALLOWED_ORIGINS}
      KEYCLOAK_BFF_DASHBOARD_ALLOWED_REDIRECT_URIS: ${KEYCLOAK_BFF_DASHBOARD_ALLOWED_REDIRECT_URIS}
      KC_DB: dev-file
    command:
      - start-dev
      - --import-realm
      - --http-port=8080
      - --proxy-headers=xforwarded
      - --hostname=${KEYCLOAK_HOSTNAME}

  electrs:
    extends:
      file: common-services.yml
      service: electrs
    environment:
      ELECTRS_NETWORK: testnet
      ELECTRS_DAEMON_RPC_ADDR: bitcoin-core:18332
      ELECTRS_DAEMON_P2P_ADDR: bitcoin-core:18333

  balance-collector:
    extends:
        file: common-services.yml
        service: balance-collector
