services:

  key-service:
    extends:
        file: common-services.yml
        service: key-service

  treasury-service:
    extends:
        file: common-services.yml
        service: treasury-service

  swap-service:
    extends:
        file: common-services.yml
        service: swap-service

  quote-service:
    extends:
        file: common-services.yml
        service: quote-service

  wallet-aggregator:
    extends:
        file: common-services.yml
        service: wallet-aggregator


  surrealdb:
    extends:
        file: common-services.yml
        service: surrealdb

  cdk_mint:
    extends:
        file: common-services.yml
        service: cdk-mintd

  ebpp:
    extends:
        file: common-services.yml
        service: ebpp

  ebill-service:
    extends:
        file: common-services.yml
        service: ebill-service

  bff-wallet-service:
    extends:
        file: common-services.yml
        service: bff-wallet-service

  bff-dashboard-service:
    extends:
        file: common-services.yml
        service: bff-dashboard-service

  bitcoin-core:
    extends:
        file: common-services.yml
        service: bitcoin-core
    command:
      -printtoconsole
      -regtest=1
      -conf=/home/bitcoin/bitcoin.conf
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-regtest", "getconnectioncount"]

  electrs:
    extends:
        file: common-services.yml
        service: electrs
    environment:
      - ELECTRS_NETWORK: regtest
      - ELECTRS_DAEMON_RPC_ADDR: bitcoin-core:18443
      - ELECTRS_DAEMON_P2P_ADDR: bitcoin-core:18444

  keycloak:
    extends:
        file: common-services.yml
        service: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: dev-file
      KC_HEALTH_ENABLED: true
      KEYCLOAK_BFF_DASHBOARD_SECRET: cute-kitties
      WDC_DASHBOARD_URL: "http://localhost:5173"
      KEYCLOAK_BFF_DASHBOARD_ALLOWED_ORIGINS: "*"
      KEYCLOAK_BFF_DASHBOARD_ALLOWED_REDIRECT_URIS: "*"
    command:
      - start-dev
      - --import-realm
      - --http-port=8080

  e2e-tests:
    image: wildcat/e2e-tests
    depends_on:
      swap-service:
        condition: service_started
      quote-service:
        condition: service_started
      wallet-aggregator:
        condition: service_healthy
      bff-wallet-service:
        condition: service_started
      bff-dashboard-service:
        condition: service_started
      key-service:
        condition: service_healthy
      surrealdb:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    volumes:
      - ./docker/e2e-tests/config.toml:/e2e-tests/config.toml
