services:

  key-service:
    build:
      context: .
      dockerfile: ./docker/key-service/Dockerfile
    ports:
      - "3335:3335"
    depends_on:
      surrealdb:
        condition: service_healthy
    volumes:
      - ./docker/key-service/config.toml:/key-service/config.toml
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3335/api-docs/openapi.json"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s
      start_interval: 3s

  treasury-service:
    build:
      context: .
      dockerfile: ./docker/treasury-service/Dockerfile
    ports:
      - "3336:3336"
    depends_on:
      surrealdb:
        condition: service_healthy
    volumes:
      - ./docker/treasury-service/config.toml:/treasury-service/config.toml

  swap-service:
    build:
      context: .
      dockerfile: ./docker/swap-service/Dockerfile
    ports:
      - "3337:3337"
    depends_on:
      surrealdb:
        condition: service_healthy
      key-service:
        condition: service_started
    volumes:
      - ./docker/swap-service/config.toml:/swap-service/config.toml

  quote-service:
    build:
      context: .
      dockerfile: ./docker/quote-service/Dockerfile
    ports:
      - "3338:3338"
    depends_on:
      surrealdb:
        condition: service_healthy
      key-service:
        condition: service_started
      treasury-service:
        condition: service_started
    volumes:
      - ./docker/quote-service/config.toml:/quote-service/config.toml
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3338/api-docs/openapi.json"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s
      start_interval: 3s

  surrealdb:
    image: surrealdb/surrealdb:latest
    volumes:
      - ./data/surrealdb:/data
    command:
      - start
      - --unauthenticated
      - rocksdb:/data/database.db
    user: ${UID}:${GID}
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "/surreal", "is-ready" ]
      interval: 5s
      retries: 5
