services:

  key-service:
    build:
      context: .
      dockerfile: ./docker/key-service/Dockerfile
    ports:
      - "3335:3335"
    depends_on:
      surrealdb:
        condition: service_healthy
    volumes:
      - ./docker/key-service/config.toml:/key-service/config.toml
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3335/api-docs/openapi.json"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s
      start_interval: 3s

  treasury-service:
    build:
      context: .
      dockerfile: ./docker/treasury-service/Dockerfile
    ports:
      - "3336:3336"
    depends_on:
      surrealdb:
        condition: service_healthy
    volumes:
      - ./docker/treasury-service/config.toml:/treasury-service/config.toml
      - ./.docker_data/treasury-service/:/data/

  swap-service:
    build:
      context: .
      dockerfile: ./docker/swap-service/Dockerfile
    ports:
      - "3337:3337"
    depends_on:
      surrealdb:
        condition: service_healthy
      key-service:
        condition: service_healthy
    volumes:
      - ./docker/swap-service/config.toml:/swap-service/config.toml

  quote-service:
    build:
      context: .
      dockerfile: ./docker/quote-service/Dockerfile
    ports:
      - "3338:3338"
    depends_on:
      surrealdb:
        condition: service_healthy
      key-service:
        condition: service_healthy
      treasury-service:
        condition: service_started
    volumes:
      - ./docker/quote-service/config.toml:/quote-service/config.toml
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3338/api-docs/openapi.json"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s
      start_interval: 3s

  surrealdb:
    image: surrealdb/surrealdb:latest
    volumes:
      - ./.docker_data/surrealdb:/data
    command:
      - start
      - --unauthenticated
      - rocksdb:/data/database.db
    user: ${UID}:${GID}
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "/surreal", "is-ready" ]
      interval: 5s
      retries: 5

  cdk_mint:
    image: thesimplekid/cdk-mintd:v0.7.4@sha256:9da05978f0e18a11ff08a2f6494d87bc2efdc1d70f733278f0c5dd4f74db1579
    restart: unless-stopped
    environment:
      - CDK_MINTD_URL=https://example.com
      - CDK_MINTD_LN_BACKEND=fakewallet
      - CDK_MINTD_LISTEN_HOST=0.0.0.0
      - CDK_MINTD_LISTEN_PORT=8085
      - CDK_MINTD_MNEMONIC=abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about
      - CDK_MINTD_DATABASE=redb
      - CDK_MINTD_CACHE_BACKEND=memory
    command: ["cdk-mintd"]
    ports:
      - "8085:8085"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://127.0.0.1:8085/v1/info || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s
      start_interval: 3s
