[package]
name = "bcr-wdc-ebill-service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = {workspace = true, features = ["macros"]}
log = {workspace = true, features = ["serde"]}
env_logger.workspace = true
config.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = {workspace = true, features = ["signal", "time"]}
bcr-ebill-api = {git = "https://github.com/BitcreditProtocol/E-Bill.git", branch = "406-anonymous-mode"} #temp until it's merged and released
bcr-ebill-transport = {git = "https://github.com/BitcreditProtocol/E-Bill.git", branch = "406-anonymous-mode"} #temp until it's merged and released
rustls = "0.23"
