[package]
name = "bcr-wdc-treasury-client"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bcr-wdc-webapi = {workspace = true}
cashu.workspace = true
chrono.workspace = true
reqwest = {workspace = true, features = ["json"]}
thiserror.workspace = true
url.workspace = true
uuid.workspace = true
