[package]
name = "bcr-wdc-treasury-client"
version = "0.1.0"
edition = "2021"

[dependencies]
bcr-wdc-webapi = { path = "../bcr-wdc-webapi" }
cashu.workspace = true
chrono.workspace = true
reqwest = {workspace = true, features = ["json"]}
thiserror.workspace = true
url = {version = "2.4"}
uuid.workspace = true
