[package]
name = "bcr-wdc-treasury-service"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum = {workspace = true, features = ["macros"]}
bcr-wdc-key-client = { path = "../bcr-wdc-key-client" }
bcr-wdc-utils = { path = "../bcr-wdc-utils" }
bcr-wdc-swap-client = { path = "../bcr-wdc-swap-client" }
bcr-wdc-webapi = { path = "../bcr-wdc-webapi" }
bitcoin.workspace = true
borsh = { workspace = true }
cashu = { workspace = true, features = ["wallet"]}
cdk = {workspace = true, default-features = false, features = ["wallet"]}
cdk-common = {workspace = true}
cdk-redb = { workspace = true }
chrono.workspace = true
config.workspace = true
env_logger.workspace = true
futures = {workspace = true}
itertools = {workspace = true}
log = {workspace = true, features = ["serde"]}
serde.workspace = true
serde_json = {workspace = true}
surrealdb.workspace = true
thiserror.workspace = true
tokio = {workspace = true, features = ["signal"]}
uuid.workspace = true

[dev-dependencies]
bcr-wdc-utils = { path = "../bcr-wdc-utils" , features = ["test-utils"] }
bcr-wdc-swap-service = { path = "../bcr-wdc-swap-service", features = ["test-utils"] }
mockall.workspace = true
rand.workspace = true
secp256k1 = {workspace = true, features = ["global-context"]}
surrealdb = {workspace = true, features = ["kv-mem"]}
