
bind_address = "0.0.0.0:3338"
log_level = "DEBUG"

[appcfg.crsat_keys_service]
url = "http://key-service:3338"

[appcfg.crsat_repo]
connection = "ws://surrealdb:8000"
namespace = "test"
database = "treasury"
secrets = "secrets"
counters = "counters"
signatures = "signatures"
proofs = "proofs"

[appcfg.sat_wallet]
mint_url = "http://cdk_mint:8085"
storage = "/data/cdk-wallet-redb.redb"

[appcfg.proof_client]
url = "http://swap-service:3338"
