
bind_address = "0.0.0.0:3338"
log_level = "DEBUG"

[appcfg]
cdk_mint_url = "http://cdk_mint:8085"
wallet_redb_storage = "/data/cdk-wallet-redb.redb"

[appcfg.crsat_repo]
connection = "ws://surrealdb:8000"
namespace = "test"
database = "credit"
secrets = "secrets"
counters = "counters"
signatures = "signatures"
