
[info]
url = "https://example.com"
listen_host = "0.0.0.0"
listen_port = 8085
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"

[info.http_cache]
backend = "memory"
ttl = 60
tti = 60

[database]
engine = "sqlite"

[ln]
ln_backend = "grpcprocessor"

[fake_wallet]
supported_units = ["sat"]
fee_percent = 0.00
reserve_fee_min = 1
min_delay_time = 1
max_delay_time = 3

[grpc_processor]
supported_units = ["sat"]
addr = "http://ebpp"
port = 9090
