[package]
name = "bcr-wdc-wallet-aggregator"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[features]
test-utils = ["axum-test"]

[dependencies]
async-trait.workspace = true
axum = {workspace = true, features = ["macros"]}
axum-test = {workspace = true, optional = true}
bcr-wdc-ebpp-client = {workspace = true}
bcr-wdc-key-client = {workspace = true}
bcr-wdc-swap-client = {workspace = true}
bcr-wdc-treasury-client = {workspace = true}
built = {workspace = true, features = ["semver", "chrono"]}
cashu.workspace = true
cdk = {workspace = true, features = ["wallet"]}
config = {workspace = true}
futures = {workspace = true}
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-http = { version = "0.6.2" }
tracing = {workspace = true }
tracing-log = {workspace = true}
tracing-subscriber = {workspace = true}
utoipa = {workspace = true, features = ["axum_extras"]}
utoipa-swagger-ui = {workspace = true, features = ["axum"]}

[dev-dependencies]
mockall.workspace = true
bcr-wdc-utils = {workspace = true, features = ["test-utils"]}

[build-dependencies]
built = {workspace = true, features = ["dependency-tree", "chrono"]}
