[package]
name = "bcr-wdc-swap-service"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
bcr-wdc-key-client = { path = "../bcr-wdc-key-client" }
cashu.workspace = true
chrono.workspace = true
config.workspace = true
env_logger.workspace = true
futures.workspace = true
itertools = {version = "0.14"}
log.workspace = true
serde.workspace = true
surrealdb.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
bcr-wdc-keys = { path = "../bcr-wdc-keys", features = ["test-utils"] }
bip39 = {version = "2"}
mockall.workspace = true
rand.workspace = true
