
bind_address = "0.0.0.0:3338"
log_level = "DEBUG"


[appcfg.quotes]
connection = "ws://surrealdb:8000"
namespace = "test"
database = "quote"
table = "quotes"

[appcfg.keys]
base_url = "http://key-service:3335"

[appcfg.wallet]
base_url = "http://treasury-service:3336"
