
bind_address = "0.0.0.0:3338"
log_level = "DEBUG"

[appcfg]
clowder_rest_url = "http://clowder-node:3010"

[appcfg.quotes]
connection = "ws://surrealdb:8000"
namespace = "test"
database = "quote"
table = "quotes"

[appcfg.keys]
base_url = "http://key-service:3338"

[appcfg.ebill_client]
base_url = "http://ebill-service:3338"
