web_bind_address = "0.0.0.0:3010"
nats_url = "nats://nats:4222"
log_level = "DEBUG"

pubsub_server_name = "localhost"
pubsub_socket_addr = "0.0.0.0:5001"
pubsub_use_gso = true

[electrum_config]
rpc_url = "tcp://electrs:50001"
network = "regtest"

[beta_params]
offline_seconds = 15
interim_seconds = 90
rabid_seconds = 3600
hashchain_buffer_size = 16384
max_download_length = 8192
multisig_m_blocks = 3
offline_frequency_check_seconds = 3
lock_reduction_per_hop_seconds = 600
rabid_audit = false # mark mint as rabid on collateralization violations
eiou_sats = 1.0 # fake exchange rate of eiou to sats
melt_margin_sats = 200
signing_request_timeout_seconds = 5
rabid_validation = true

[alpha_params]
melt_rebroadcast_interval_seconds = 5
melt_timeout_seconds = 30

# Clowder Configurations

[[nodes]]
public_key = "03f4c9d0124b4207c598ed0efb7b5b65b0404499ba26bbe821e3d1275c30f9fb27"
socket_addr = "clowder-node:5001"
rest_url = "http://clowder-node:3010"
server_name = "localhost"
mint_url = "http://bff-wallet-service:4343"

[[nodes]]
public_key = "022a2ad6548211a0eff9a61c236194ae4c3c2f10fd35446108794a76d220786c2b"
socket_addr = "clowder-beta:5002"
rest_url = "http://clowder-beta:3011"
server_name = "localhost"
mint_url = "https://google.com:443"

[[clowders]]
alpha = "03f4c9d0124b4207c598ed0efb7b5b65b0404499ba26bbe821e3d1275c30f9fb27"
betas = [
    "022a2ad6548211a0eff9a61c236194ae4c3c2f10fd35446108794a76d220786c2b"
]
aggregated_key = "028456fbc3cd559484c4c01a9bccfbc517169f1b84ed21d09a6ab557e352e4ce04"

[[clowders]]
alpha = "022a2ad6548211a0eff9a61c236194ae4c3c2f10fd35446108794a76d220786c2b"
betas = [
    "03f4c9d0124b4207c598ed0efb7b5b65b0404499ba26bbe821e3d1275c30f9fb27"
]
aggregated_key = "027cab05fc66340dac97c7444d8149bab8c9330774440c0da41737ecade46d3579"
