
log_level = "DEBUG"
bind_address = "0.0.0.0:3338"

[appcfg]

grpc_address = "0.0.0.0:9090"
electrum_url = "electrs:50001"
refresh_interval_secs=30
treasury_service_public_key = "0234dd69c56c36a41230d573d68adeae0030c9bc0bf26f24d3e1b64c604d293c68"

[appcfg.onchain]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
network = "testnet"
store_path = "/data/testnet"
stop_gap = 2
max_confirmation_blocks = 2
avg_transaction_size_bytes = 300


[appcfg.private_keys]
connection = "ws://surrealdb:8000"
namespace = "test"
database = "ebpp"
table = "privates"

[appcfg.payments]
connection = "ws://surrealdb:8000"
namespace = "test"
database = "ebpp"
incoming_payments_table = "incomings"
outgoing_payments_table = "outgoings"
