bind_address = "0.0.0.0:3338"
log_level = "DEBUG"

[appcfg.ebill_db]
connection = "ws://surrealdb:8000"
namespace = "test"
database = "ebill"

[appcfg.nostr_cfg]
relays = ["wss://bitcr-cloud-run-05-550030097098.europe-west1.run.app"]
only_known_contacts = false

[appcfg]
bitcoin_network = "testnet"
esplora_base_url = "https://esplora.minibill.tech"
data_dir = "./"
job_runner_initial_delay_seconds = 1
job_runner_check_interval_seconds = 600

