[package]
name = "bcr-wdc-eiou-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bcr-wdc-webapi = {workspace = true}
reqwest = {workspace = true, features = ["json"]}
thiserror.workspace = true
