[package]
name = "bcr-wdc-utils"
version.workspace = true
edition.workspace = true
license.workspace = true


[features]
test-utils = ["rand"]


[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bitcoin = { workspace = true}
borsh = {workspace = true}
cashu = {workspace = true, features = ["swagger"]}
cdk-common = {workspace = true}
chrono.workspace = true
itertools = {workspace = true}
rand = {workspace = true, optional  = true}
reqwest = {workspace = true, features = ["json"]}
secp256k1 = {workspace = true, features = ["global-context"]}
serde = {workspace = true, features = ["derive"]}
thiserror.workspace = true
tokio = {workspace = true, features = ["time", "rt"]}
tracing = {workspace = true}
url.workspace = true
uuid.workspace = true

[dev-dependencies]
rand = {workspace = true}
