[package]
name = "bcr-wdc-utils"
version.workspace = true
edition.workspace = true
license.workspace = true


[features]
test-utils = ["rand"]


[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bitcoin = { workspace = true}
borsh = {workspace = true}
cashu = {workspace = true, features = ["swagger"]}
cdk-common = {workspace = true}
chrono.workspace = true
itertools = {workspace = true}
rand = {workspace = true, optional  = true}
secp256k1 = {workspace = true, features = ["global-context"]}
thiserror.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
rand = {workspace = true}
