[package]
name = "bcr-web-api"
version = "0.1.0"
edition = "2021"


[dependencies]
cdk.workspace = true
chrono.workspace = true
rust_decimal.workspace = true
serde.workspace = true
uuid.workspace = true
