[package]
name = "bcr-wdc-key-client"
version = "0.1.0"
edition = "2021"

[dependencies]
cashu.workspace = true
reqwest = { version = "0.12", features = ["json"] }
thiserror.workspace = true
url = {version = "2.4"}

