daemon_rpc_addr = "bitcoin-core:18332"
daemon_p2p_addr="bitcoin-core:18333"
db_dir = "/data/storage/index"
network = "testnet"
electrum_rpc_addr = "0.0.0.0:50001"
log_filters = "INFO"
auth="electrs:bitcredit"
