[package]
name = "bcr-wdc-swap-client"
version = "0.1.0"
edition = "2021"

[dependencies]
bcr-wdc-webapi = { path = "../bcr-wdc-webapi" }
cashu.workspace = true
chrono.workspace = true
reqwest = { version = "0.12", features = ["json"] }
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
# bcr-wdc-swap-service = {features = ["test-utils"], path = "../bcr-wdc-swap-service"}
bcr-wdc-keys = {path = "../bcr-wdc-keys", features = ["test-utils"]}
tokio.workspace = true
