[package]
name = "bcr-wdc-webapi"
version = "0.1.0"
edition = "2021"


[dependencies]
bcr-ebill-core.workspace = true
bdk_wallet = {workspace = true}
bitcoin.workspace = true
borsh = {workspace = true, features = ["derive"]}
cashu = {workspace = true, features = ["swagger"]}
chrono.workspace = true
rust_decimal.workspace = true
serde.workspace = true
strum = {workspace = true, features = ["derive"]}
utoipa = {workspace = true, features = ["chrono", "uuid", "decimal"]}
uuid = {workspace = true, features = ["serde"]}
