[package]
name = "bcr-wdc-webapi"
version = "0.1.0"
edition = "2021"


[dependencies]
cdk.workspace = true
chrono.workspace = true
rust_decimal.workspace = true
serde.workspace = true
utoipa.workspace = true
uuid.workspace = true
