[package]
name = "bcr-wdc-webapi"
version = "0.1.0"
edition = "2021"
license = "MIT"


[lib]
name = "bcr_wdc_webapi"
path = "src/lib.rs"

[[bin]]
name = "bcr-wdc-webapi-devtool"
path = "src/bin/devtool.rs"
required-features = ["test-utils"]

[dependencies]
bcr-ebill-core.workspace = true
bcr-wdc-utils = {workspace = true, features = ["test-utils"] }
bdk_wallet = {workspace = true}
bitcoin.workspace = true
borsh = {workspace = true, features = ["derive"]}
cashu = {workspace = true, features = ["swagger"]}
chrono.workspace = true
rand = {workspace = true}
rust_decimal.workspace = true
serde.workspace = true
strum = {workspace = true, features = ["derive"]}
utoipa = {workspace = true, features = ["chrono", "uuid", "decimal"]}
uuid = {workspace = true, features = ["serde"]}

[features]
default = []
test-utils = []
