
bind_address = "0.0.0.0:3337"
log_level = "DEBUG"


[appcfg.proof_db]
connection = "ws://surrealdb:8000"
namespace = "test"
database = "swap"
table = "proofs"


[appcfg.keys_cl]
base_url = "http://key-service:3335"
