
bind_address = "0.0.0.0:3338"
log_level = "DEBUG"

[appcfg]
cdk_mint_url = "http://cdk-mintd:8085"
keys_client_url = "http://key-service:3338"
swap_client_url = "http://swap-service:3338"
treasury_client_url = "http://treasury-service:3338"

