name: End to end integration test

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Docker Compose
      run: |
        echo $(uname -s)-$(uname -m)
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.36.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
        sudo chmod +x /usr/local/bin/docker-compose && \
        docker-compose --version

    - name: Create Github App token
      id: app-token
      uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
      with:
        app-id: ${{ vars.PRIVATE_REPO_ACCESS_APP_ID }}
        private-key: ${{ secrets.PRIVATE_REPO_ACCESS_APP_PRIVATE_KEY }}
        owner: BitcreditProtocol

    - name: Git auth with app token
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: |
        git config --global url."https://x-access-token:${GH_TOKEN}@github.com/".insteadOf "https://github.com/"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.0

    - name: Build Base Image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: .
        file: docker/base-image/Dockerfile
        tags: wildcat/base-image
        build-args: |
          CARGO_NET_GIT_FETCH_WITH_CLI=true
        secrets: |
          "gh_token=${{ steps.app-token.outputs.token }}"
        push: false
        load: true

    - name: Build Docker Key Service
      run: docker build -t wildcat/key-service -f docker/key-service/Dockerfile .
    - name: Build Docker Treasury Service
      run: docker build -t wildcat/treasury-service -f docker/treasury-service/Dockerfile .
    - name: Build Docker Swap Service
      run: docker build -t wildcat/swap-service -f docker/swap-service/Dockerfile .
    - name: Build Docker Quote Service
      run: docker build -t wildcat/quote-service -f docker/quote-service/Dockerfile .
    - name: Build Docker Wallet Aggregator
      run: docker build -t wildcat/wallet-aggregator -f docker/wallet-aggregator/Dockerfile .
    - name: Build Docker EBPP
      run: docker build -t wildcat/ebpp -f docker/ebpp/Dockerfile .
    - name: Build Docker Ebill Service
      run: docker build -t wildcat/ebill-service -f docker/ebill-service/Dockerfile .
    - name: Build Docker E2E Tests
      run: docker build -t wildcat/e2e-tests -f docker/e2e-tests/Dockerfile .
    - name: Run E2E Tests
      run: docker-compose -f docker-compose-e2e.yml --verbose up --exit-code-from e2e-tests --abort-on-container-exit e2e-tests
    - name: Tear Down E2E Environment
      if: always()
      run: docker-compose -f docker-compose-e2e.yml --verbose down
