name: build and push nightly Docker images

on:
  push:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

env:
    PROJECT_ID: "bitcr-shared"
    GAR_LOCATION: "europe-west1"
    REPOSITORY: "bitcr-wildcat-dev"
    GAR_PATH: "europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev"
    BASE_IMAGE_NAME: "wildcat/base-image"
    BASE_IMAGE_CACHE: "europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/wildcat-base-cache"
    BASE_TAR: "base-image.tar"

jobs:

# ───────────────────────────────
# build base image, cache, upload local artifact
# ───────────────────────────────
  base-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Authenticate to GCP
      id: auth
      uses: google-github-actions/auth@ba79af03959ebeac9769e648f473a284504d9193 # v2.1.10
      with:
        workload_identity_provider: ${{ secrets.GCLOUD_WIF_PROVIDER }}
        service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
        token_format: access_token

    - name: Auth w/ registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

    - name: Build base image (remote cache, local load)
      run: |
        CACHE_TAG="${GITHUB_REF_NAME//\//-}"
        DOCKER_BUILDKIT=1 docker buildx build \
          --platform linux/amd64 \
          --file docker/base-image/Dockerfile \
          --tag "${BASE_IMAGE_NAME}" \
          --cache-from=type=registry,ref="${BASE_IMAGE_CACHE}:${CACHE_TAG}" \
          --cache-to=type=registry,ref="${BASE_IMAGE_CACHE}:${CACHE_TAG}",mode=max \
          --output type=docker,dest="${BASE_TAR}",name="${BASE_IMAGE_NAME}" \
          .

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: base-image
        path: "${{ env.BASE_TAR }}"
        retention-days: 1

# ───────────────────────────────
# build & push wildcat images
# ───────────────────────────────
  wildcat-images:
    needs: base-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    strategy:
      fail-fast: false
      #max-parallel: 1
      matrix:
        service:
          - name: bcr-wdc-key-service
            dockerfile: docker/key-service/Dockerfile
          - name: bcr-wdc-treasury-service
            dockerfile: docker/treasury-service/Dockerfile
          - name: bcr-wdc-swap-service
            dockerfile: docker/swap-service/Dockerfile
          - name: bcr-wdc-quote-service
            dockerfile: docker/quote-service/Dockerfile
          - name: bcr-wdc-wallet-aggregator
            dockerfile: docker/wallet-aggregator/Dockerfile
          - name: bcr-wdc-ebpp
            dockerfile: docker/ebpp/Dockerfile
          - name: bcr-wdc-ebill-service
            dockerfile: docker/ebill-service/Dockerfile
          - name: bcr-wdc-eiou-service
            dockerfile: docker/eiou-service/Dockerfile
          - name: bcr-wdc-balance-collector
            dockerfile: docker/balance-collector/Dockerfile

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Authenticate to GCP
      id: auth
      uses: google-github-actions/auth@ba79af03959ebeac9769e648f473a284504d9193 # v2.1.10
      with:
        workload_identity_provider: ${{ secrets.GCLOUD_WIF_PROVIDER }}
        service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
        token_format: access_token

    - name: Auth w/ registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      with:
        driver: docker


    - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: base-image
        path: .

    - name: Load base image
      run: docker load -i "${BASE_TAR}"

    - id: meta
      name: Metadata for ${{ matrix.service.name }}
      uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
      with:
        images: ${{ env.GAR_PATH }}/${{ matrix.service.name }}
        tags: |
          type=raw,value=nightly

    - id: push
      name: Build & push ${{ matrix.service.name }}
      uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6.17.0
      with:
        context: .
        file: ${{ matrix.service.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        # Uncomment for per-service cache
        # cache-from: type=registry,ref=${{ env.GAR_PATH }}/${{ matrix.service.name }}:buildcache
        # cache-to:   type=registry,ref=${{ env.GAR_PATH }}/${{ matrix.service.name }}:buildcache,mode=max

    # ─────────────────────────────
    # provenance
    # ─────────────────────────────
    - uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd # v2.3.0
      with:
        subject-name: ${{ env.GAR_PATH }}/${{ matrix.service.name }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true

    # ─────────────────────────────
    # deploy to dev
    # ─────────────────────────────

  deploy-dev:
    name: Deploy to dev
    needs: wildcat-images

    permissions:
      contents: read
      deployments: write
      id-token: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref_name }}
      cancel-in-progress: true

    ##############################################################
    # -> wildcat-dev-docker
    runs-on: [self-hosted, wildcat-dev-docker]    
    environment: dev

    env:
      GAR_LOCATION: ${{ vars.GAR_LOCATION }}
      DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}
      DATA_PATH: ${{ vars.DATA_PATH }}
      NGINX_PATH: ${{ vars.NGINX_PATH }}
      MINT_SEED_PHRASE: ${{ secrets.MINT_SEED_PHRASE }}
      MINT_IDENTITY: ${{ secrets.MINT_IDENTITY }}


    steps:
      - name: 'Environment Check'
        run: |
          echo "--------------------------------------------------"
          echo "Checking hostname:"
          hostname
          echo "--------------------------------------------------"
          echo "I am running in this directory:"
          pwd
          echo "--------------------------------------------------"
          echo "My user is:"
          whoami
          echo "--------------------------------------------------"
          echo "Verifying user ID and group memberships..."
          id

      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Mirror repo to ${{ env.DEPLOY_PATH }}
        run: |
          set -euo pipefail
          mkdir -p ${{ env.DEPLOY_PATH }}
          rsync -a --no-owner --no-group --delete --exclude '.git' ./ ${{ env.DEPLOY_PATH }}/

      
      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@ba79af03959ebeac9769e648f473a284504d9193 # v2.1.10
        with:
          workload_identity_provider: ${{ secrets.GCLOUD_WIF_PROVIDER }}
          service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
          token_format: access_token

      - name: Auth w/ registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: 'Create .env file'
        run: |
          echo "Creating .env file..."
          cat <<EOF > .env
          # This file is generated by a GitHub Action.
          
          IMAGE_TAG=nightly

          DATA_PATH=${{ env.DATA_PATH }}

          # Dashboard
          WDC_DASHBOARD_URL="${{ secrets.WDC_DASHBOARD_URL }}"

          # Keycloak
          KEYCLOAK_HOSTNAME=${{ secrets.KEYCLOAK_HOSTNAME }}
          KEYCLOAK_ADMIN_USER=${{ secrets.KEYCLOAK_ADMIN_USER }}
          KEYCLOAK_ADMIN_SECRET="${{ secrets.KEYCLOAK_ADMIN_SECRET }}"
          KEYCLOAK_BFF_DASHBOARD_SECRET="${{ secrets.KEYCLOAK_BFF_DASHBOARD_SECRET }}"
          KEYCLOAK_BFF_DASHBOARD_ALLOWED_REDIRECT_URIS="${{ secrets.KEYCLOAK_BFF_DASHBOARD_ALLOWED_REDIRECT_URIS }}"
          KEYCLOAK_BFF_DASHBOARD_ALLOWED_ORIGINS="${{ secrets.KEYCLOAK_BFF_DASHBOARD_ALLOWED_ORIGINS }}"

          # Testnet Configuration
          BITCOIN_NETWORK=${{ vars.BITCOIN_NETWORK }}
          BITCOIN_NETWORK_COMMAND_ARG=${{ vars.BITCOIN_NETWORK_COMMAND_ARG }}
          BITCOIN_CLI_NETWORK_ARG=${{ vars.BITCOIN_CLI_NETWORK_ARG }}
          ELECTRS_NETWORK=${{ vars.ELECTRS_NETWORK }}
          ELECTRS_DAEMON_RPC_ADDR=${{ vars.ELECTRS_DAEMON_RPC_ADDR }}
          ELECTRS_DAEMON_P2P_ADDR=${{ vars.ELECTRS_DAEMON_P2P_ADDR }}

          UID=1000
          GID=1000

          EOF
        working-directory: ${{ env.DEPLOY_PATH }}
    
      - name: Validate compose config
        run: |
          docker compose \
          -f docker-compose.yml \
          -f deployment-configuration.yml \
          config --quiet
        working-directory: ${{ env.DEPLOY_PATH }}

      - name: 'Pull Latest Images'
        id: pull
        run: |
            docker compose \
            -f docker-compose.yml \
            -f deployment-configuration.yml \
            pull
        working-directory: ${{ env.DEPLOY_PATH }}

      - name: 'Tear Down Previous Deployment'
        run: |
            docker compose \
            -f docker-compose.yml \
            -f deployment-configuration.yml \
            down --remove-orphans --timeout 30
        working-directory: ${{ env.DEPLOY_PATH }}
        continue-on-error: true

      - name: 'Deploy'
        run: |
            docker compose \
            -f docker-compose.yml \
            -f deployment-configuration.yml \
            up -d --force-recreate
        working-directory: ${{ env.DEPLOY_PATH }}

      - name: Check running services
        run: |
          docker compose ps --services --filter "status=running"
          docker compose ps --services --filter "status=healthy"
          docker compose logs --tail=100
        working-directory: ${{ env.DEPLOY_PATH }}

      - name: Docker system prune
        run: |
          docker system prune -f --filter "until=24h" --filter "dangling=true"

          
    
      - name: 'Restart nginx reverse proxy'
        run: |
          docker compose up -d --force-recreate --remove-orphans
        working-directory: ${{ env.NGINX_PATH }}