name: Test base image git auth token
on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

env:
    PROJECT_ID: "bitcr-shared"
    GAR_LOCATION: "europe-west1"
    REPOSITORY: "bitcr-wildcat-dev"
    GAR_PATH: "europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev"
    BASE_IMAGE_NAME: "wildcat/base-image"
    BASE_IMAGE_CACHE: "europe-west1-docker.pkg.dev/bitcr-shared/bitcr-wildcat-dev/wildcat-base-cache-test"
    BASE_TAR: "base-image.tar"

jobs:
  base-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Create Github App token
      id: app-token
      uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
      with:
        app-id: ${{ vars.PRIVATE_REPO_ACCESS_APP_ID }}
        private-key: ${{ secrets.PRIVATE_REPO_ACCESS_APP_PRIVATE_KEY }}
        owner: BitcreditProtocol

    - name: Git auth with app token
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: |
        git config --global url."https://x-access-token:${GH_TOKEN}@github.com/".insteadOf "https://github.com/"

    - name: Authenticate to GCP
      id: auth
      uses: google-github-actions/auth@ba79af03959ebeac9769e648f473a284504d9193 # v2.1.10
      with:
        workload_identity_provider: ${{ secrets.GCLOUD_WIF_PROVIDER }}
        service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
        token_format: access_token

    - name: Auth w/ registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

    - name: Build base image (cache + local tar)
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/base-image/Dockerfile
        push: false
        platforms: linux/amd64
        tags: ${{ env.BASE_IMAGE_NAME }}
        build-args: |
          CARGO_NET_GIT_FETCH_WITH_CLI=true
        secrets: |
          "gh_token=${{ steps.app-token.outputs.token }}"
        cache-from: |
          type=registry,ref=${{ env.BASE_IMAGE_CACHE }}:buildcache
        cache-to: |
          type=registry,ref=${{ env.BASE_IMAGE_CACHE }}:buildcache,mode=max
        outputs: |
          type=docker,dest=${{ env.BASE_TAR }},name=${{ env.BASE_IMAGE_NAME }}
      

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: base-image
        path: "${{ env.BASE_TAR }}"
        retention-days: 1