name: GCP Registry Push Test

on:
  workflow_dispatch:
  push:
    branches:
      - cleot/test-gcp-registry
  

permissions:
  contents: read
  # id-token: write # For Workload Identity Federation

jobs:
  test-gar-push:
    runs-on: ubuntu-latest
    concurrency:
      group: gcp-registry-test-${{ github.ref }}
      cancel-in-progress: true

    env:
      PROJECT_ID: "bitcr-shared"
      GAR_LOCATION: "europe-west1"
      REPOSITORY: "bitcr-wildcat-dev"
      TEST_IMAGE_NAME: "simple-test-image"

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet


    # test image
    - name: Create dummy Dockerfile
      run: |
        echo "FROM alpine:latest" > Dockerfile.test
        echo "LABEL description=\"Simple test image for GAR push verification\"" >> Dockerfile.test
        echo "RUN echo \"Test image build timestamp: $(date)\"" >> Dockerfile.test
        echo "CMD echo \"GAR push test image executed successfully!\"" >> Dockerfile.test
        echo "--- Dockerfile.test contents ---"
        cat Dockerfile.test
        echo "------------------------------"


    - name: Build, push, and verify
      env:
        LOCAL_TAG: ${{ env.TEST_IMAGE_NAME }}:local-build
        REMOTE_TAG_SHA: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.TEST_IMAGE_NAME }}:${{ github.sha }}
        REMOTE_TAG_TEST: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.TEST_IMAGE_NAME }}:latest-test
      run: |
        export DOCKER_BUILDKIT=1
        docker build -t "$LOCAL_TAG" -f Dockerfile.test .
        docker tag "$LOCAL_TAG" "$REMOTE_TAG_SHA"
        docker tag "$LOCAL_TAG" "$REMOTE_TAG_TEST"
        docker push "$REMOTE_TAG_SHA" "$REMOTE_TAG_TEST"
        docker pull "$REMOTE_TAG_SHA"

